export const RoutePath = {
  BASE: '/',
  ACCOUNT: '/account',
  CREATE_POST: '/create-post',
  CREATE_QUESTION: '/create-question',
  EDIT_POST: '/edit-post',
  EDIT_QUESTION: '/edit-question',
  HOME: '/home',
  LOGIN: '/login',
  MY_POSTS: '/my-posts',
  POST_COMMENTS: '/post/:postId/comments',
  QUESTIONS_LIST: '/questions-list',
  REGISTER: '/register',
  USER: '/user/:userId',
  USERS_LIST: '/users-list',
  NOT_FOUND: '*',
} as const;
